export const majorCitiesArray = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Surat",
  "Agra",
  "Varanasi",
  "Coimbatore",
  "Chandigarh",
  "Ludhiana",
  "Raipur",
  "Patna",
  "Ranchi",
  "Guwahati",
  "Amritsar",
  "Vijayawada",
  "Nashik",
  "Madurai",
  "Mysore",
  "Aurangabad",
  "Cuttack",
  "Bhubaneswar",
  "Salem",
  "Tiruchirappalli",
  "Kota",
  "Kochi (Cochin)",
  "Aligarh",
  "Bareilly",
  "Moradabad",
  "Jalandhar",
  "Jamshedpur",
  "Dehradun",
  "Dhanbad",
  "Gorakhpur",
  "Warangal",
  "Guntur",
  "Jammu",
  "Jalgaon",
  "Nellore",
  "Ajmer",
  "Bikaner",
  "Srinagar",
  "Amravati",
  "Rajahmundry",
  "Shimla",
  "Tirupati",
  "Ujjain",
  "Siliguri",
  "Nanded",
  "Rourkela",
  "Durgapur",
  "Allahabad",
  "Davanagere",
  "Jhansi",
  "Asansol",
  "Tirunelveli",
  "Kolhapur",
  "Gwalior",
  "Latur",
  "Gandhinagar",
  "Noida",
  "Thiruvananthapuram",
  "Meerut",
  "Mathura",
  "Bilaspur",
  "Solapur",
  "Dhule",
  "Durg",
  "Gaya",
  "Nalanda",
  "Bhagalpur",
  "Saharsa",
  "Rohtak",
  "Hisar",
  "Panipat",
  "Sonipat",
  "Karnal",
  "Rewari",
  "Palwal",
  "Bahadurgarh",
  "Yamunanagar",
  "Kurukshetra",
  "Faridabad",
  "Panchkula",
  "Ambala",
  
];

export const specialtiesArray = [
  "General Medicine",
  "Pediatrics",
  "Obstetrics and Gynecology",
  "Cardiology",
  "Dermatology",
  "Orthopedics",
  "Ophthalmology",
  "Gastroenterology",
  "Neurology",
  "Psychiatry",
  "Nephrology",
  "Urology",
  "Radiology",
  "Anesthesiology",
  "Oncology",
  "Pulmonology",
  "Rheumatology",
  "Endocrinology",
  "Hematology",
  "Infectious Disease",
  "Family Medicine",
  "Geriatrics",
  "Allergy and Immunology",
  "Physical Medicine and Rehabilitation",
  "Emergency Medicine",
  "Otolaryngology (ENT)",
  "Plastic Surgery",
  "Vascular Surgery",
  "Pediatric Surgery",
  "Neurosurgery",
  "Thoracic Surgery",
  "Pain Medicine",
  "Sports Medicine",
  "Pathology",
  "Gynecologic Oncology",
  "Neonatology",
  "Forensic Medicine",
  "Palliative Medicine",
  "Sleep Medicine",
  "Reproductive Medicine",
  "Interventional Radiology",
  "Nuclear Medicine",
  "Clinical Genetics",
  "Addiction Medicine",
  "Aerospace Medicine",
  "Colorectal Surgery",
  "Hand Surgery",
  "Infectious Disease Medicine",
  "Interventional Cardiology",
  "Medical Genetics",
  "General Dentistry",
  "Orthodontics",
  "Pediatric Dentistry (Pedodontics)",
  "Oral and Maxillofacial Surgery",
  "Periodontics",
  "Prosthodontics",
  "Endodontics",
  "Oral Pathology",
  "Dental Public Health",
  "Oral Medicine",
  "Cosmetic Dentistry",
  "Implant Dentistry",
  "Restorative Dentistry"
];


export const doctorArray =[

    {
      "name": "Dr. Rohan Verma",
      "degree": "General Medicine",
      "age": 38,
      "experience": 12,
      "gender": "Male",
      "rating": 4.8,
      "fees": "300",
      "city": "Varanasi",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Sneha Gupta",
      "age": 40,
      "degree": "Emergency Medicine",
      "experience": 15,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Bhopal",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Sanjay Patel",
      "age": 55,
      "degree": "Pediatric Dentistry (Pedodontics)",
      "experience": 28,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Jaipur",
      "state": "Rajasthan"
    },
    {
      "name": "Dr. Priya Singh",
      "age": 32,
      "degree": "Urology",
      "experience": 10,
      "gender": "Female",
      "rating": 5,
      "fees": "450",
      "city": "Delhi",
      "state": "Delhi"
    },
    {
      "name": "Dr. Karthik Reddy",
      "age": 48,
      "degree": "Gynecologic Oncology",
      "experience": 22,
      "gender": "Male",
      "rating": 4,
      "fees": "300",
      "city": "Pune",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Nisha Sharma",
      "age": 34,
      "degree": "General Medicine",
      "experience": 18,
      "gender": "Female",
      "rating": 3,
      "fees": "350",
      "city": "Thiruvananthapuram",
      "state": "Kerala"
    },
    {
      "name": "Dr. Anil Kumar",
      "age": 42,
      "degree": "General Medicine",
      "experience": 12,
      "gender": "Male",
      "rating": 4,
      "fees": "200",
      "city": "Kolkata",
      "state": "West Bengal"
    },
    {
      "name": "Dr. Ramesh Singh",
      "age": 49,
      "degree": "Physical Medicine and Rehabilitation",
      "experience": 20,
      "gender": "Male",
      "rating": 3,
      "fees": "300",
      "city": "Lucknow",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Meera Rao",
      "age": 29,
      "degree": "General Medicine",
      "experience": 7,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Mumbai",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Vishal Reddy",
      "age": 50,
      "degree": "Neurosurgery",
      "experience": 25,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Mumbai",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Sunita Menon",
      "age": 35,
      "degree": "General Medicine",
      "experience": 14,
      "gender": "Female",
      "rating": 4,
      "fees": "250",
      "city": "Hyderabad",
      "state": "Telangana"
    },
    {
      "name": "Dr. Anand Desai",
      "age": 45,
      "degree": "General Medicine",
      "experience": 21,
      "gender": "Male",
      "rating": 3,
      "fees": "400",
      "city": "Hyderabad",
      "state": "Telangana"
    },
    {
      "name": "Dr. Rekha Sharma",
      "age": 33,
      "degree": "Interventional Radiology",
      "experience": 9,
      "gender": "Female",
      "rating": 2,
      "fees": "300",
      "city": "Bangalore",
      "state": "Karnataka"
    },
    {
      "name": "Dr. Ravi Joshi",
      "age": 52,
      "degree": "Cosmetic Dentistry",
      "experience": 27,
      "gender": "Male",
      "rating": 4,
      "fees": "250",
      "city": "Nagpur",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Deepa Patel",
      "age": 30,
      "degree": "Anesthesiology",
      "experience": 10,
      "gender": "Female",
      "rating": 3,
      "fees": "350",
      "city": "Indore",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Anita Sharma",
      "age": 45,
      "degree": "Obstetrics and Gynecology",
      "experience": 18,
      "gender": "Female",
      "rating": 4,
      "fees": "0",
      "city": "Chandigarh",
      "state": "Chandigarh"
    },
    {
      "name": "Dr. Sunil Gupta",
      "age": 40,
      "degree": "Orthopedics",
      "experience": 15,
      "gender": "Male",
      "rating": 5,
      "fees": "450",
      "city": "Raipur",
      "state": "Chhattisgarh"
    },
    {
      "name": "Dr. Priyanka Menon",
      "age": 38,
      "degree": "General Medicine",
      "experience": 20,
      "gender": "Female",
      "rating": 4,
      "fees": "300",
      "city": "Coimbatore",
      "state": "Tamil Nadu"
    },
    {
      "name": "Dr. Rajiv Kumar",
      "age": 47,
      "degree": "Dermatology",
      "experience": 25,
      "gender": "Male",
      "rating": 4,
      "fees": "400",
      "city": "Ranchi",
      "state": "Jharkhand"
    },
    {
      "name": "Dr. Ananya Choudhury",
      "age": 41,
      "degree": "Nuclear Medicine",
      "experience": 19,
      "gender": "Female",
      "rating": 3,
      "fees": "350",
      "city": "Guwahati",
      "state": "Assam"
    },
    {
      "name": "Dr. Mohan Kumar",
      "age": 35,
      "degree": "Pediatrics",
      "experience": 14,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Amritsar",
      "state": "Punjab"
    },
    {
      "name": "Dr. Anjali Singh",
      "age": 42,
      "degree": "Rheumatology",
      "experience": 18,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Vijayawada",
      "state": "Andhra Pradesh"
    },
    {
      "name": "Dr. Ravi Kumar",
      "age": 50,
      "degree": "Endocrinology",
      "experience": 22,
      "gender": "Male",
      "rating": 4,
      "fees": "300",
      "city": "Nashik",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Anjali Reddy",
      "age": 29,
      "degree": "Hematology",
      "experience": 7,
      "gender": "Female",
      "rating": 5,
      "fees": "250",
      "city": "Madurai",
      "state": "Tamil Nadu"
    },
    {
      "name": "Dr. Arun Sharma",
      "age": 45,
      "degree": "Infectious Disease",
      "experience": 22,
      "gender": "Male",
      "rating": 4,
      "fees": "400",
      "city": "Kochi (Cochin)",
      "state": "Kerala"
    },
    {
      "name": "Dr. Pooja Patel",
      "age": 38,
      "degree": "Family Medicine",
      "experience": 16,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Ludhiana",
      "state": "Punjab"
    },
    {
      "name": "Dr. Vivek Menon",
      "age": 52,
      "degree": "Allergy and Immunology",
      "experience": 26,
      "gender": "Male",
      "rating": 3,
      "fees": "300",
      "city": "Raipur",
      "state": "Chhattisgarh"
    },
    {
      "name": "Dr. Meena Sharma",
      "age": 30,
      "degree": "Physical Medicine and Rehabilitation",
      "experience": 12,
      "gender": "Female",
      "rating": 5,
      "fees": "250",
      "city": "Patna",
      "state": "Bihar"
    },
    {
      "name": "Dr. Rajeev Verma",
      "age": 45,
      "degree": "Emergency Medicine",
      "experience": 20,
      "gender": "Male",
      "rating": 4,
      "fees": "400",
      "city": "Nellore",
      "state": "Andhra Pradesh"
    },
    {
      "name": "Dr. Anu Gupta",
      "age": 32,
      "degree": "Otolaryngology (ENT)",
      "experience": 10,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Ajmer",
      "state": "Rajasthan"
    },
    {
      "name": "Dr. Arjun Menon",
      "age": 47,
      "degree": "Plastic Surgery",
      "experience": 21,
      "gender": "Male",
      "rating": 3,
      "fees": "300",
      "city": "Bikaner",
      "state": "Rajasthan"
    },
    {
      "name": "Dr. Reena Singh",
      "age": 34,
      "degree": "Vascular Surgery",
      "experience": 17,
      "gender": "Female",
      "rating": 4,
      "fees": "250",
      "city": "Srinagar",
      "state": "Jammu and Kashmir"
    },
    {
      "name": "Dr. Abhinav Reddy",
      "age": 31,
      "degree": "Pediatric Surgery",
      "experience": 9,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Amravati",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Neha Sharma",
      "age": 40,
      "degree": "Neurosurgery",
      "experience": 19,
      "gender": "Female",
      "rating": 3,
      "fees": "300",
      "city": "Rajahmundry",
      "state": "Andhra Pradesh"
    },
    {
      "name": "Dr. Suresh Kumar",
      "age": 39,
      "degree": "Thoracic Surgery",
      "experience": 18,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Shimla",
      "state": "Himachal Pradesh"
    },
    {
      "name": "Dr. Ananya Desai",
      "age": 44,
      "degree": "Pain Medicine",
      "experience": 20,
      "gender": "Female",
      "rating": 4,
      "fees": "250",
      "city": "Tirupati",
      "state": "Andhra Pradesh"
    },
    {
      "name": "Dr. Arvind Sharma",
      "age": 37,
      "degree": "Sports Medicine",
      "experience": 15,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Ujjain",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Priyanka Patel",
      "age": 41,
      "degree": "Pathology",
      "experience": 19,
      "gender": "Female",
      "rating": 3,
      "fees": "350",
      "city": "Siliguri",
      "state": "West Bengal"
    },
    {
      "name": "Dr. Surya Menon",
      "age": 33,
      "degree": "Gynecologic Oncology",
      "experience": 14,
      "gender": "Male",
      "rating": 4,
      "fees": "300",
      "city": "Nanded",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Rina Sharma",
      "age": 36,
      "degree": "Neonatology",
      "experience": 16,
      "gender": "Female",
      "rating": 4,
      "fees": "250",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rahul Gupta",
      "age": 49,
      "degree": "Forensic Medicine",
      "experience": 23,
      "gender": "Male",
      "rating": 3,
      "fees": "400",
      "city": "Durgapur",
      "state": "West Bengal"
    },
    {
      "name": "Dr. Ananya Kumar",
      "age": 30,
      "degree": "Palliative Medicine",
      "experience": 10,
      "gender": "Female",
      "rating": 5,
      "fees": "300",
      "city": "Allahabad",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Vikas Sharma",
      "age": 42,
      "degree": "Sleep Medicine",
      "experience": 20,
      "gender": "Male",
      "rating": 4,
      "fees": "250",
      "city": "Davanagere",
      "state": "Karnataka"
    },
    {
      "name": "Dr. Seema Patel",
      "age": 28,
      "degree": "Reproductive Medicine",
      "experience": 9,
      "gender": "Female",
      "rating": 3,
      "fees": "350",
      "city": "Jhansi",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Arvind Kumar",
      "age": 45,
      "degree": "Interventional Radiology",
      "experience": 22,
      "gender": "Male",
      "rating": 4,
      "fees": "300",
      "city": "Asansol",
      "state": "West Bengal"
    },
    {
      "name": "Dr. Neetu Reddy",
      "age": 32,
      "degree": "Nuclear Medicine",
      "experience": 11,
      "gender": "Female",
      "rating": 5,
      "fees": "250",
      "city": "Tirunelveli",
      "state": "Tamil Nadu"
    },
    {
      "name": "Dr. Vinay Sharma",
      "age": 39,
      "degree": "Clinical Genetics",
      "experience": 18,
      "gender": "Male",
      "rating": 4,
      "fees": "400",
      "city": "Kolhapur",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Meenakshi Patel",
      "age": 27,
      "degree": "Addiction Medicine",
      "experience": 8,
      "gender": "Female",
      "rating": 3,
      "fees": "300",
      "city": "Gwalior",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Alok Kumar",
      "age": 47,
      "degree": "Aerospace Medicine",
      "experience": 23,
      "gender": "Male",
      "rating": 4,
      "fees": "250",
      "city": "Latur",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Rekha Menon",
      "age": 36,
      "degree": "Colorectal Surgery",
      "experience": 15,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Gandhinagar",
      "state": "Gujarat"
    },
    {
      "name": "Dr. Ajay Kumar",
      "age": 52,
      "degree": "Hand Surgery",
      "experience": 26,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Noida",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Anita Reddy",
      "age": 32,
      "degree": "Infectious Disease Medicine",
      "experience": 11,
      "gender": "Female",
      "rating": 3,
      "fees": "300",
      "city": "Thiruvananthapuram",
      "state": "Kerala"
    },
    {
      "name": "Dr. Sunil Sharma",
      "age": 38,
      "degree": "Interventional Cardiology",
      "experience": 17,
      "gender": "Male",
      "rating": 4,
      "fees": "250",
      "city": "Meerut",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Priya Menon",
      "age": 41,
      "degree": "Medical Genetics",
      "experience": 20,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Mathura",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Rahul Reddy",
      "age": 35,
      "degree": "General Dentistry",
      "experience": 14,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Bilaspur",
      "state": "Chhattisgarh"
    },
    {
      "name": "Dr. Nisha Kumar",
      "age": 39,
      "degree": "Orthodontics",
      "experience": 18,
      "gender": "Female",
      "rating": 3,
      "fees": "300",
      "city": "Solapur",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Vinod Reddy",
      "age": 44,
      "degree": "Pediatric Dentistry (Pedodontics)",
      "experience": 21,
      "gender": "Male",
      "rating": 4,
      "fees": "250",
      "city": "Dhule",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Meenakshi Menon",
      "age": 37,
      "degree": "Oral and Maxillofacial Surgery",
      "experience": 16,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Durg",
      "state": "Chhattisgarh"
    },
    {
      "name": "Dr. Rajesh Sharma",
      "age": 42,
      "degree": "Periodontics",
      "experience": 19,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Gaya",
      "state": "Bihar"
    },
    {
      "name": "Dr. Priyanka Kumar",
      "age": 33,
      "degree": "Prosthodontics",
      "experience": 12,
      "gender": "Female",
      "rating": 4,
      "fees": "250",
      "city": "Nalanda",
      "state": "Bihar"
    },
    {
      "name": "Dr. Anil Reddy",
      "age": 48,
      "degree": "Endodontics",
      "experience": 24,
      "gender": "Male",
      "rating": 3,
      "fees": "300",
      "city": "Bhagalpur",
      "state": "Bihar"
    },
    {
      "name": "Dr. Rina Menon",
      "age": 35,
      "degree": "Oral Pathology",
      "experience": 14,
      "gender": "Female",
      "rating": 5,
      "fees": "350",
      "city": "Saharsa",
      "state": "Bihar"
    },
    {
      "name": "Dr. Sanjay Kumar",
      "age": 40,
      "degree": "Dental Public Health",
      "experience": 18,
      "gender": "Male",
      "rating": 4,
      "fees": "400",
      "city": "Rohtak",
      "state": "Haryana"
    },
    {
      "name": "Dr. Ananya Reddy",
      "age": 37,
      "degree": "Oral Medicine",
      "experience": 16,
      "gender": "Female",
      "rating": 3,
      "fees": "350",
      "city": "Hisar",
      "state": "Haryana"
    },
    {
      "name": "Dr. Rakesh Kumar",
      "age": 49,
      "degree": "Cosmetic Dentistry",
      "experience": 24,
      "gender": "Male",
      "rating": 4,
      "fees": "300",
      "city": "Panipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Seema Sharma",
      "age": 38,
      "degree": "Implant Dentistry",
      "experience": 15,
      "gender": "Female",
      "rating": 4,
      "fees": "250",
      "city": "Sonipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Rajeev Reddy",
      "age": 42,
      "degree": "Restorative Dentistry",
      "experience": 18,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Karnal",
      "state": "Haryana"
    },
    {
      "name": "Dr. Anu Kumar",
      "age": 36,
      "degree": "General Medicine",
      "experience": 16,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Ambala",
      "state": "Haryana"
    },
    {
      "name": "Dr. Manish Verma",
      "age": 45,
      "degree": "Neonatology",
      "experience": 18,
      "gender": "Male",
      "rating": 4,
      "fees": "300",
      "city": "Delhi",
      "state": "Delhi"
    },
    {
      "name": "Dr. Ritu Kapoor",
      "age": 39,
      "degree": "Orthopedics",
      "experience": 16,
      "gender": "Female",
      "rating": 3,
      "fees": "250",
      "city": "Mumbai",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Sunil Kumar",
      "age": 34,
      "degree": "Gastroenterology",
      "experience": 22,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Bangalore",
      "state": "Karnataka"
    },
    {
      "name": "Dr. Pooja Sharma",
      "age": 28,
      "degree": "Cardiology",
      "experience": 12,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Chennai",
      "state": "Tamil Nadu"
    },
    {
      "name": "Dr. Rahul Reddy",
      "age": 51,
      "degree": "Dermatology",
      "experience": 25,
      "gender": "Male",
      "rating": 4,
      "fees": "280",
      "city": "Hyderabad",
      "state": "Telangana"
    },
    {
      "name": "Dr. Nandini Desai",
      "age": 37,
      "degree": "Ophthalmology",
      "experience": 10,
      "gender": "Female",
      "rating": 3,
      "fees": "200",
      "city": "Pune",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Rajesh Kumar",
      "age": 43,
      "degree": "Pediatrics",
      "experience": 20,
      "gender": "Male",
      "rating": 4,
      "fees": "300",
      "city": "Kolkata",
      "state": "West Bengal"
    },
    {
      "name": "Dr. Smita Gupta",
      "age": 36,
      "degree": "Nephrology",
      "experience": 15,
      "gender": "Female",
      "rating": 5,
      "fees": "450",
      "city": "Jaipur",
      "state": "Rajasthan"
    },
    {
      "name": "Dr. Arvind Sharma",
      "age": 49,
      "degree": "Psychiatry",
      "experience": 28,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Lucknow",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Meena Patel",
      "age": 33,
      "degree": "Urology",
      "experience": 17,
      "gender": "Female",
      "rating": 3,
      "fees": "320",
      "city": "Ahmedabad",
      "state": "Gujarat"
    },
    {
      "name": "Dr. Abhishek Joshi",
      "age": 29,
      "degree": "Family Medicine",
      "experience": 11,
      "gender": "Male",
      "rating": 4,
      "fees": "280",
      "city": "Bhopal",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Ananya Verma",
      "age": 44,
      "degree": "Hematology",
      "experience": 19,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Chandigarh",
      "state": "Chandigarh"
    },
    {
      "name": "Dr. Sanjay Sharma",
      "age": 57,
      "degree": "Endocrinology",
      "experience": 31,
      "gender": "Male",
      "rating": 3,
      "fees": "320",
      "city": "Nagpur",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Anjali Reddy",
      "age": 40,
      "degree": "Radiology",
      "experience": 14,
      "gender": "Female",
      "rating": 4,
      "fees": "360",
      "city": "Indore",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Amit Singh",
      "age": 35,
      "degree": "Pulmonology",
      "experience": 23,
      "gender": "Male",
      "rating": 2,
      "fees": "260",
      "city": "Thane",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Deepika Kapoor",
      "age": 42,
      "degree": "Rheumatology",
      "experience": 18,
      "gender": "Female",
      "rating": 5,
      "fees": "390",
      "city": "Bhubaneswar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajeev Nair",
      "age": 30,
      "degree": "Infectious Disease",
      "experience": 9,
      "gender": "Male",
      "rating": 3,
      "fees": "220",
      "city": "Kanpur",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Priyanka Deshmukh",
      "age": 46,
      "degree": "Geriatrics",
      "experience": 20,
      "gender": "Female",
      "rating": 4,
      "fees": "370",
      "city": "Nashik",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Ajay Gupta",
      "age": 32,
      "degree": "Allergy and Immunology",
      "experience": 10,
      "gender": "Male",
      "rating": 4,
      "fees": "280",
      "city": "Guwahati",
      "state": "Assam"
    },
    {
      "name": "Dr. Suman Kumar",
      "age": 49,
      "degree": "Physical Medicine and Rehabilitation",
      "experience": 27,
      "gender": "Female",
      "rating": 3,
      "fees": "340",
      "city": "Rajkot",
      "state": "Gujarat"
    },
    {
      "name": "Dr. Ramesh Sharma",
      "age": 38,
      "degree": "Emergency Medicine",
      "experience": 13,
      "gender": "Male",
      "rating": 2,
      "fees": "240",
      "city": "Patna",
      "state": "Bihar"
    },
    {
      "name": "Dr. Sangeeta Verma",
      "age": 54,
      "degree": "Otolaryngology (ENT)",
      "experience": 29,
      "gender": "Female",
      "rating": 5,
      "fees": "410",
      "city": "Bilaspur",
      "state": "Chhattisgarh"
    },
    {
      "name": "Dr. Pradeep Kumar",
      "age": 41,
      "degree": "Plastic Surgery",
      "experience": 18,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Kota",
      "state": "Rajasthan"
    },
    {
      "name": "Dr. Meenakshi Singh",
      "age": 47,
      "degree": "Vascular Surgery",
      "experience": 25,
      "gender": "Female",
      "rating": 5,
      "fees": "430",
      "city": "Bhubaneswar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sandeep Sharma",
      "age": 39,
      "degree": "Pediatric Surgery",
      "experience": 14,
      "gender": "Male",
      "rating": 3,
      "fees": "320",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Suman Verma",
      "age": 28,
      "degree": "Neurosurgery",
      "experience": 9,
      "gender": "Female",
      "rating": 4,
      "fees": "290",
      "city": "Jamshedpur",
      "state": "Jharkhand"
    },
    {
      "name": "Dr. Arjun Kumar",
      "age": 36,
      "degree": "Thoracic Surgery",
      "experience": 18,
      "gender": "Male",
      "rating": 2,
      "fees": "260",
      "city": "Gandhinagar",
      "state": "Gujarat"
    },
    {
      "name": "Dr. Priya Reddy",
      "age": 43,
      "degree": "Pain Medicine",
      "experience": 17,
      "gender": "Female",
      "rating": 4,
      "fees": "330",
      "city": "Noida",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Sameer Joshi",
      "age": 30,
      "degree": "Sports Medicine",
      "experience": 8,
      "gender": "Male",
      "rating": 3,
      "fees": "240",
      "city": "Thiruvananthapuram",
      "state": "Kerala"
    },
    {
      "name": "Dr. Seema Sharma",
      "age": 29,
      "degree": "Pathology",
      "experience": 6,
      "gender": "Female",
      "rating": 4,
      "fees": "280",
      "city": "Meerut",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Sunil Verma",
      "age": 47,
      "degree": "Gynecologic Oncology",
      "experience": 22,
      "gender": "Male",
      "rating": 5,
      "fees": "420",
      "city": "Mathura",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Preeti Sharma",
      "age": 41,
      "degree": "Neonatology",
      "experience": 19,
      "gender": "Female",
      "rating": 3,
      "fees": "310",
      "city": "Bilaspur",
      "state": "Chhattisgarh"
    },
    {
      "name": "Dr. Suresh Kumar",
      "age": 32,
      "degree": "Forensic Medicine",
      "experience": 11,
      "gender": "Male",
      "rating": 4,
      "fees": "290",
      "city": "Rohtak",
      "state": "Haryana"
    },
    {
      "name": "Dr. Sneha Gupta",
      "age": 38,
      "degree": "Palliative Medicine",
      "experience": 17,
      "gender": "Female",
      "rating": 2,
      "fees": "250",
      "city": "Hisar",
      "state": "Haryana"
    },
    {
      "name": "Dr. Amit Kumar",
      "age": 53,
      "degree": "Sleep Medicine",
      "experience": 28,
      "gender": "Male",
      "rating": 5,
      "fees": "410",
      "city": "Panipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Deepa Nair",
      "age": 40,
      "degree": "Reproductive Medicine",
      "experience": 15,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Sonipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Rajat Kumar",
      "age": 36,
      "degree": "Interventional Radiology",
      "experience": 13,
      "gender": "Male",
      "rating": 3,
      "fees": "320",
      "city": "Karnal",
      "state": "Haryana"
    },
    {
      "name": "Dr. Anjali Singh",
      "age": 39,
      "degree": "Nuclear Medicine",
      "experience": 16,
      "gender": "Female",
      "rating": 4,
      "fees": "330",
      "city": "Ambala",
      "state": "Haryana"
    },
    {
      "name": "Dr. Mohit Sharma",
      "age": 31,
      "degree": "Clinical Genetics",
      "experience": 9,
      "gender": "Male",
      "rating": 2,
      "fees": "280",
      "city": "Rewari",
      "state": "Haryana"
    },
    {
      "name": "Dr. Priyanka Verma",
      "age": 50,
      "degree": "Addiction Medicine",
      "experience": 27,
      "gender": "Female",
      "rating": 4,
      "fees": "380",
      "city": "Palwal",
      "state": "Haryana"
    },
    {
      "name": "Dr. Vinod Kumar",
      "age": 29,
      "degree": "Aerospace Medicine",
      "experience": 8,
      "gender": "Male",
      "rating": 5,
      "fees": "420",
      "city": "Bahadurgarh",
      "state": "Haryana"
    },
    {
      "name": "Dr. Anu Sharma",
      "age": 38,
      "degree": "Colorectal Surgery",
      "experience": 17,
      "gender": "Female",
      "rating": 3,
      "fees": "310",
      "city": "Yamunanagar",
      "state": "Haryana"
    },
    {
      "name": "Dr. Rajeev Verma",
      "age": 47,
      "degree": "Hand Surgery",
      "experience": 24,
      "gender": "Male",
      "rating": 4,
      "fees": "360",
      "city": "Kurukshetra",
      "state": "Haryana"
    },
    {
      "name": "Dr. Neha Singh",
      "age": 34,
      "degree": "Infectious Disease Medicine",
      "experience": 14,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Faridabad",
      "state": "Haryana"
    },
    {
      "name": "Dr. Amit Verma",
      "age": 38,
      "degree": "Interventional Cardiology",
      "experience": 17,
      "gender": "Male",
      "rating": 3,
      "fees": "330",
      "city": "Panchkula",
      "state": "Haryana"
    },
    {
      "name": "Dr. Sangeeta Sharma",
      "age": 43,
      "degree": "Medical Genetics",
      "experience": 19,
      "gender": "Female",
      "rating": 4,
      "fees": "370",
      "city": "Ambala",
      "state": "Haryana"
    },
    {
      "name": "Dr. Rajiv Gupta",
      "age": 32,
      "degree": "General Dentistry",
      "experience": 10,
      "gender": "Male",
      "rating": 5,
      "fees": "410",
      "city": "Gurgaon",
      "state": "Haryana"
    },
    {
      "name": "Dr. Sneha Patel",
      "age": 40,
      "degree": "Orthodontics",
      "experience": 16,
      "gender": "Female",
      "rating": 2,
      "fees": "250",
      "city": "Panipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Anil Sharma",
      "age": 47,
      "degree": "Pediatric Dentistry (Pedodontics)",
      "experience": 23,
      "gender": "Male",
      "rating": 4,
      "fees": "360",
      "city": "Hisar",
      "state": "Haryana"
    },
    {
      "name": "Dr. Priya Reddy",
      "age": 33,
      "degree": "Oral and Maxillofacial Surgery",
      "experience": 12,
      "gender": "Female",
      "rating": 5,
      "fees": "410",
      "city": "Sonipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Amit Kumar",
      "age": 44,
      "degree": "Periodontics",
      "experience": 21,
      "gender": "Male",
      "rating": 3,
      "fees": "340",
      "city": "Karnal",
      "state": "Haryana"
    },
    {
      "name": "Dr. Anjali Verma",
      "age": 35,
      "degree": "Prosthodontics",
      "experience": 15,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Ambala",
      "state": "Haryana"
    },
    {
      "name": "Dr. Manoj Kumar",
      "age": 39,
      "degree": "Endodontics",
      "experience": 18,
      "gender": "Male",
      "rating": 2,
      "fees": "270",
      "city": "Rewari",
      "state": "Haryana"
    },
    {
      "name": "Dr. Pooja Sharma",
      "age": 29,
      "degree": "Oral Pathology",
      "experience": 8,
      "gender": "Female",
      "rating": 4,
      "fees": "300",
      "city": "Bahadurgarh",
      "state": "Haryana"
    },
    {
      "name": "Dr. Sunil Verma",
      "age": 55,
      "degree": "Dental Public Health",
      "experience": 27,
      "gender": "Male",
      "rating": 3,
      "fees": "320",
      "city": "Ambala",
      "state": "Haryana"
    },
    {
      "name": "Dr. Meena Gupta",
      "age": 41,
      "degree": "Oral Medicine",
      "experience": 19,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Hisar",
      "state": "Haryana"
    },
    {
      "name": "Dr. Ajay Kumar",
      "age": 48,
      "degree": "Cosmetic Dentistry",
      "experience": 23,
      "gender": "Male",
      "rating": 4,
      "fees": "370",
      "city": "Panipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Sneha Sharma",
      "age": 30,
      "degree": "Implant Dentistry",
      "experience": 10,
      "gender": "Female",
      "rating": 3,
      "fees": "250",
      "city": "Sonipat",
      "state": "Haryana"
    },
    {
      "name": "Dr. Anil Kumar",
      "age": 56,
      "degree": "Restorative Dentistry",
      "experience": 30,
      "gender": "Male",
      "rating": 5,
      "fees": "430",
      "city": "Karnal",
      "state": "Haryana"
    },
    {
      "name": "Dr. Preeti Verma",
      "age": 37,
      "degree": "General Medicine",
      "experience": 16,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Delhi",
      "state": "Delhi"
    },
    {
      "name": "Dr. Ravi Gupta",
      "age": 42,
      "degree": "Pediatrics",
      "experience": 19,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Mumbai",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Smita Reddy",
      "age": 32,
      "degree": "Obstetrics and Gynecology",
      "experience": 12,
      "gender": "Female",
      "rating": 3,
      "fees": "280",
      "city": "Bangalore",
      "state": "Karnataka"
    },
    {
      "name": "Dr. Arvind Kumar",
      "age": 52,
      "degree": "Cardiology",
      "experience": 27,
      "gender": "Male",
      "rating": 4,
      "fees": "330",
      "city": "Chennai",
      "state": "Tamil Nadu"
    },
    {
      "name": "Dr. Suman Verma",
      "age": 37,
      "degree": "Dermatology",
      "experience": 15,
      "gender": "Female",
      "rating": 5,
      "fees": "450",
      "city": "Hyderabad",
      "state": "Telangana"
    },
    {
      "name": "Dr. Rajesh Kumar",
      "age": 45,
      "degree": "Orthopedics",
      "experience": 20,
      "gender": "Male",
      "rating": 4,
      "fees": "380",
      "city": "Pune",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Nandini Sharma",
      "age": 39,
      "degree": "Ophthalmology",
      "experience": 17,
      "gender": "Female",
      "rating": 3,
      "fees": "320",
      "city": "Kolkata",
      "state": "West Bengal"
    },
    {
      "name": "Dr. Abhishek Verma",
      "age": 35,
      "degree": "Gastroenterology",
      "experience": 14,
      "gender": "Male",
      "rating": 2,
      "fees": "270",
      "city": "Jaipur",
      "state": "Rajasthan"
    },
    {
      "name": "Dr. Ritu Kapoor",
      "age": 43,
      "degree": "Neurology",
      "experience": 22,
      "gender": "Female",
      "rating": 4,
      "fees": "350",
      "city": "Lucknow",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Sunil Reddy",
      "age": 31,
      "degree": "Psychiatry",
      "experience": 10,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Ahmedabad",
      "state": "Gujarat"
    },
    {
      "name": "Dr. Pooja Sharma",
      "age": 29,
      "degree": "Nephrology",
      "experience": 8,
      "gender": "Female",
      "rating": 4,
      "fees": "300",
      "city": "Bhopal",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Amit Verma",
      "age": 48,
      "degree": "Urology",
      "experience": 23,
      "gender": "Male",
      "rating": 3,
      "fees": "320",
      "city": "Nashik",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Anjali Sharma",
      "age": 40,
      "degree": "Radiology",
      "experience": 16,
      "gender": "Female",
      "rating": 2,
      "fees": "250",
      "city": "Indore",
      "state": "Madhya Pradesh"
    },
    {
      "name": "Dr. Suresh Kumar",
      "age": 52,
      "degree": "Anesthesiology",
      "experience": 27,
      "gender": "Male",
      "rating": 3,
      "fees": "270",
      "city": "Thane",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Meenakshi Reddy",
      "age": 36,
      "degree": "Oncology",
      "experience": 14,
      "gender": "Female",
      "rating": 4,
      "fees": "340",
      "city": "Bhubaneswar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajeev Sharma",
      "age": 54,
      "degree": "Pulmonology",
      "experience": 24,
      "gender": "Male",
      "rating": 5,
      "fees": "420",
      "city": "Kanpur",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Priyanka Reddy",
      "age": 38,
      "degree": "Hematology",
      "experience": 17,
      "gender": "Female",
      "rating": 4,
      "fees": "370",
      "city": "Nagpur",
      "state": "Maharashtra"
    },
    {
      "name": "Dr. Suman Verma",
      "age": 43,
      "degree": "Emergency Medicine",
      "experience": 18,
      "gender": "Female",
      "rating": 3,
      "fees": "310",
      "city": "Jamshedpur",
      "state": "Jharkhand"
    },
    {
      "name": "Dr. Arjun Kumar",
      "age": 33,
      "degree": "Neurosurgery",
      "experience": 11,
      "gender": "Male",
      "rating": 2,
      "fees": "260",
      "city": "Gandhinagar",
      "state": "Gujarat"
    },
    {
      "name": "Dr. Pooja Verma",
      "age": 41,
      "degree": "Thoracic Surgery",
      "experience": 19,
      "gender": "Female",
      "rating": 5,
      "fees": "430",
      "city": "Noida",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Sanjay Sharma",
      "age": 35,
      "degree": "Pain Medicine",
      "experience": 14,
      "gender": "Male",
      "rating": 4,
      "fees": "330",
      "city": "Thiruvananthapuram",
      "state": "Kerala"
    },
    {
      "name": "Dr. Sangeeta Verma",
      "age": 36,
      "degree": "Pathology",
      "experience": 16,
      "gender": "Female",
      "rating": 3,
      "fees": "290",
      "city": "Meerut",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Rajesh Kumar",
      "age": 50,
      "degree": "Gynecologic Oncology",
      "experience": 25,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Mathura",
      "state": "Uttar Pradesh"
    },
    {
      "name": "Dr. Anu Sharma",
      "age": 34,
      "degree": "Reproductive Endocrinology and Infertility",
      "experience": 13,
      "gender": "Female",
      "rating": 4,
      "fees": "360",
      "city": "Bilaspur",
      "state": "Chhattisgarh"
    },
    {
      "name": "Dr. Ajay Verma",
      "age": 29,
      "degree": "Interventional Radiology",
      "experience": 8,
      "gender": "Male",
      "rating": 5,
      "fees": "410",
      "city": "Rajkot",
      "state": "Gujarat"
    },
    {
      "name": "Dr. Suman Kumar",
      "age": 45,
      "degree": "Medical Toxicology",
      "experience": 21,
      "gender": "Female",
      "rating": 3,
      "fees": "320",
      "city": "Patna",
      "state": "Bihar"
    },
    {
      "name": "Dr. Meena Patel",
      "age": 47,
      "degree": "Hospice and Palliative Medicine",
      "experience": 22,
      "gender": "Female",
      "rating": 4,
      "fees": "330",
      "city": "Puri",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajesh Verma",
      "age": 36,
      "degree": "Sleep Medicine",
      "experience": 15,
      "gender": "Male",
      "rating": 2,
      "fees": "260",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Pooja Gupta",
      "age": 32,
      "degree": "Neurodevelopmental Disabilities",
      "experience": 11,
      "gender": "Female",
      "rating": 3,
      "fees": "270",
      "city": "Brahmapur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Reddy",
      "age": 49,
      "degree": "Clinical Neurophysiology",
      "experience": 28,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Priya Sharma",
      "age": 35,
      "degree": "Sleep Medicine",
      "experience": 14,
      "gender": "Female",
      "rating": 3,
      "fees": "290",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Amit Kumar",
      "age": 41,
      "degree": "Palliative Medicine",
      "experience": 19,
      "gender": "Male",
      "rating": 4,
      "fees": "310",
      "city": "Koraput",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ritu Verma",
      "age": 29,
      "degree": "Dental Public Health",
      "experience": 8,
      "gender": "Female",
      "rating": 5,
      "fees": "390",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Suresh Kumar",
      "age": 52,
      "degree": "Forensic Medicine",
      "experience": 25,
      "gender": "Male",
      "rating": 4,
      "fees": "370",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sneha Patel",
      "age": 48,
      "degree": "Pain Medicine",
      "experience": 23,
      "gender": "Female",
      "rating": 3,
      "fees": "340",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Anil Sharma",
      "age": 31,
      "degree": "Orthopedic Surgery",
      "experience": 12,
      "gender": "Male",
      "rating": 2,
      "fees": "250",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Preeti Verma",
      "age": 34,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 13,
      "gender": "Female",
      "rating": 4,
      "fees": "260",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajat Kumar",
      "age": 45,
      "degree": "Pediatric Surgery",
      "experience": 22,
      "gender": "Male",
      "rating": 5,
      "fees": "440",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sanjay Gupta",
      "age": 39,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 17,
      "gender": "Male",
      "rating": 4,
      "fees": "360",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Neha Sharma",
      "age": 32,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 11,
      "gender": "Female",
      "rating": 3,
      "fees": "280",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ajay Kumar",
      "age": 50,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 28,
      "gender": "Male",
      "rating": 5,
      "fees": "420",
      "city": "Koraput",
      "state": "Odisha"
    },
    {
      "name": "Dr. Priyanka Reddy",
      "age": 38,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 18,
      "gender": "Female",
      "rating": 4,
      "fees": "380",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Suresh Kumar",
      "age": 35,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 14,
      "gender": "Male",
      "rating": 3,
      "fees": "320",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Meenakshi Gupta",
      "age": 29,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 8,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajesh Sharma",
      "age": 48,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 23,
      "gender": "Male",
      "rating": 4,
      "fees": "360",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Verma",
      "age": 37,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 15,
      "gender": "Male",
      "rating": 3,
      "fees": "300",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Meenakshi Verma",
      "age": 34,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 13,
      "gender": "Female",
      "rating": 2,
      "fees": "280",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ravi Verma",
      "age": 52,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 29,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Smita Sharma",
      "age": 45,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 22,
      "gender": "Female",
      "rating": 5,
      "fees": "430",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Abhishek Kumar",
      "age": 39,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 19,
      "gender": "Male",
      "rating": 4,
      "fees": "370",
      "city": "Koraput",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ritu Reddy",
      "age": 32,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 11,
      "gender": "Female",
      "rating": 3,
      "fees": "330",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Kumar",
      "age": 50,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 28,
      "gender": "Male",
      "rating": "3",
      "fees": "310",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sneha Verma",
      "age": 38,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 17,
      "gender": "Female",
      "rating": 4,
      "fees": "300",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Anil Kumar",
      "age": 42,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 21,
      "gender": "Male",
      "rating": 5,
      "fees": "340",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Pooja Sharma",
      "age": 35,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 14,
      "gender": "Female",
      "rating": 3,
      "fees": "330",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Amit Sharma",
      "age": 32,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 10,
      "gender": "Male",
      "rating": 2,
      "fees": "250",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Suresh Verma",
      "age": 46,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 24,
      "gender": "Male",
      "rating": 4,
      "fees": "390",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ritu Kumar",
      "age": 29,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 8,
      "gender": "Female",
      "rating": 5,
      "fees": "370",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Sharma",
      "age": 51,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 29,
      "gender": "Male",
      "rating": 3,
      "fees": "350",
      "city": "Koraput",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sneha Kumar",
      "age": 37,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 16,
      "gender": "Female",
      "rating": 4,
      "fees": "280",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Anjali Verma",
      "age": 47,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 22,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajat Sharma",
      "age": 39,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 18,
      "gender": "Male",
      "rating": 4,
      "fees": "360",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Priya Verma",
      "age": 33,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 12,
      "gender": "Female",
      "rating": 3,
      "fees": "320",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Verma",
      "age": 47,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 23,
      "gender": "Male",
      "rating": 5,
      "fees": "410",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Meena Verma",
      "age": 36,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 15,
      "gender": "Female",
      "rating": 4,
      "fees": "380",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ajay Sharma",
      "age": 44,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 21,
      "gender": "Male",
      "rating": 2,
      "fees": "250",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Suman Verma",
      "age": 31,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 10,
      "gender": "Female",
      "rating": 3,
      "fees": "270",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Anil Kumar",
      "age": 56,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 30,
      "gender": "Male",
      "rating": 4,
      "fees": "370",
      "city": "Koraput",
      "state": "Odisha"
    },
    {
      "name": "Dr. Preeti Kumar",
      "age": 38,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 17,
      "gender": "Female",
      "rating": 5,
      "fees": "400",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ravi Kumar",
      "age": 32,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 11,
      "gender": "Male",
      "rating": 3,
      "fees": "330",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Smita Kumar",
      "age": 45,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 22,
      "gender": "Female",
      "rating": 4,
      "fees": "320",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Neha Kumar",
      "age": 38,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 18,
      "gender": "Female",
      "rating": 3,
      "fees": "280",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Amit Kumar",
      "age": 47,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 25,
      "gender": "Male",
      "rating": 5,
      "fees": "390",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Priya Sharma",
      "age": 39,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 19,
      "gender": "Female",
      "rating": 4,
      "fees": "370",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Suresh Kumar",
      "age": 34,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 13,
      "gender": "Male",
      "rating": 3,
      "fees": "350",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Meenakshi Sharma",
      "age": 33,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 12,
      "gender": "Female",
      "rating": 2,
      "fees": "250",
      "city": "Koraput",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajeev Kumar",
      "age": 41,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 20,
      "gender": "Male",
      "rating": 5,
      "fees": "420",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Anu Kumar",
      "age": 36,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 15,
      "gender": "Female",
      "rating": 4,
      "fees": "380",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ajay Kumar",
      "age": 35,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 14,
      "gender": "Male",
      "rating": 3,
      "fees": "330",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sneha Sharma",
      "age": 29,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 8,
      "gender": "Female",
      "rating": 5,
      "fees": "320",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Anil Verma",
      "age": 52,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 27,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Pooja Kumar",
      "age": 37,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 16,
      "gender": "Female",
      "rating": "3",
      "fees": "290",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ravi Sharma",
      "age": 30,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 10,
      "gender": "Male",
      "rating": 4,
      "fees": "310",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Smita Kumar",
      "age": 44,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 21,
      "gender": "Female",
      "rating": 5,
      "fees": "390",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajesh Kumar",
      "age": 34,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 13,
      "gender": "Male",
      "rating": 4,
      "fees": "370",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Kumar",
      "age": 31,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 11,
      "gender": "Male",
      "rating": 3,
      "fees": "330",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Meenakshi Sharma",
      "age": 45,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 22,
      "gender": "Female",
      "rating": 2,
      "fees": "250",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ritu Kumar",
      "age": 49,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 28,
      "gender": "Female",
      "rating": 4,
      "fees": "340",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Sharma",
      "age": 37,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 16,
      "gender": "Male",
      "rating": "3",
      "fees": "320",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Neha Kumar",
      "age": 34,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 15,
      "gender": "Female",
      "rating": 4,
      "fees": "300",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Amit Kumar",
      "age": 38,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 17,
      "gender": "Male",
      "rating": 5,
      "fees": "400",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Priya Sharma",
      "age": 32,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 12,
      "gender": "Female",
      "rating": 3,
      "fees": "360",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Suresh Kumar",
      "age": 50,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 26,
      "gender": "Male",
      "rating": 4,
      "fees": "340",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Meenakshi Verma",
      "age": 36,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 16,
      "gender": "Female",
      "rating": 5,
      "fees": "380",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ajay Sharma",
      "age": 46,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 23,
      "gender": "Male",
      "rating": "3",
      "fees": "310",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Pooja Kumar",
      "age": 30,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 10,
      "gender": "Female",
      "rating": 4,
      "fees": "330",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ravi Kumar",
      "age": 51,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 29,
      "gender": "Male",
      "rating": 5,
      "fees": "410",
      "city": "Bhadrak",
      "state": "Odisha"
    },
    {
      "name": "Dr. Smita Kumar",
      "age": 42,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 20,
      "gender": "Female",
      "rating": 4,
      "fees": "370",
      "city": "Baripada",
      "state": "Odisha"
    },
    {
      "name": "Dr. Rajesh Kumar",
      "age": 37,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 18,
      "gender": "Male",
      "rating": "2",
      "fees": "280",
      "city": "Keonjhar",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Kumar",
      "age": 34,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 13,
      "gender": "Male",
      "rating": 3,
      "fees": "270",
      "city": "Cuttack",
      "state": "Odisha"
    },
    {
      "name": "Dr. Meenakshi Sharma",
      "age": 32,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 12,
      "gender": "Female",
      "rating": 4,
      "fees": "290",
      "city": "Sambalpur",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ritu Kumar",
      "age": 48,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 25,
      "gender": "Female",
      "rating": 5,
      "fees": "390",
      "city": "Rourkela",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sunil Sharma",
      "age": 39,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 17,
      "gender": "Male",
      "rating": 4,
      "fees": "380",
      "city": "Koraput",
      "state": "Odisha"
    },
    {
      "name": "Dr. Sneha Kumar",
      "age": 36,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 15,
      "gender": "Female",
      "rating": 3,
      "fees": "320",
      "city": "Bargarh",
      "state": "Odisha"
    },
    {
      "name": "Dr. Anjali Verma",
      "age": 34,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 13,
      "gender": "Female",
      "rating": 2,
      "fees": "280",
      "city": "Balasore",
      "state": "Odisha"
    },
    {
      "name": "Dr. Ajay Kumar",
      "age": 53,
      "degree": "Orthopedic Surgery of the Spine",
      "experience": 28,
      "gender": "Male",
      "rating": 4,
      "fees": "350",
      "city": "Balasore",
      "state": "Odisha"
    },
  {
    "name": "Dr. Abhishek Sharma",
    "age": 37,
    "degree": "Obstetrics and Gynecology",
    "experience": 10,
    "gender": "Male",
    "rating": 4,
    "fees": "350",
    "city": "Delhi",
    "state": "Delhi"
  },
  {
    "name": "Dr. Sneha Patel",
    "age": 44,
    "degree": "Orthopedics",
    "experience": 18,
    "gender": "Female",
    "rating": 5,
    "fees": "450",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Rajesh Kumar",
    "age": 31,
    "degree": "Emergency Medicine",
    "experience": 6,
    "gender": "Male",
    "rating": 3,
    "fees": "200",
    "city": "Bangalore",
    "state": "Karnataka"
  },
  {
    "name": "Dr. Priya Singh",
    "age": 52,
    "degree": "Pediatric Dentistry (Pedodontics)",
    "experience": 25,
    "gender": "Female",
    "rating": 4,
    "fees": "300",
    "city": "Chennai",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Sunil Verma",
    "age": 39,
    "degree": "Urology",
    "experience": 12,
    "gender": "Male",
    "rating": 2,
    "fees": "275",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "name": "Dr. Nandini Gupta",
    "age": 48,
    "degree": "Gynecologic Oncology",
    "experience": 20,
    "gender": "Female",
    "rating": 4,
    "fees": "400",
    "city": "Kolkata",
    "state": "West Bengal"
  },
  {
    "name": "Dr. Rakesh Yadav",
    "age": 28,
    "degree": "Family Medicine",
    "experience": 5,
    "gender": "Male",
    "rating": 4,
    "fees": "250",
    "city": "Pune",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Aisha Khan",
    "age": 56,
    "degree": "Addiction Medicine",
    "experience": 30,
    "gender": "Female",
    "rating": 3,
    "fees": "320",
    "city": "Ahmedabad",
    "state": "Gujarat"
  },
  {
    "name": "Dr. Aditya Joshi",
    "age": 33,
    "degree": "Interventional Radiology",
    "experience": 14,
    "gender": "Male",
    "rating": 1,
    "fees": "180",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Deepika Sharma",
    "age": 42,
    "degree": "Cosmetic Dentistry",
    "experience": 22,
    "gender": "Female",
    "rating": 5,
    "fees": "500",
    "city": "Lucknow",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Anand Reddy",
    "age": 29,
    "degree": "Neurosurgery",
    "experience": 15,
    "gender": "Male",
    "rating": 4,
    "fees": "380",
    "city": "Chandigarh",
    "state": "Chandigarh"
  },
  {
    "name": "Dr. Meenakshi Desai",
    "age": 36,
    "degree": "Ophthalmology",
    "experience": 8,
    "gender": "Female",
    "rating": 3,
    "fees": "275",
    "city": "Nagpur",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Arjun Khanna",
    "age": 47,
    "degree": "Neonatology",
    "experience": 23,
    "gender": "Male",
    "rating": 2,
    "fees": "210",
    "city": "Indore",
    "state": "Madhya Pradesh"
  },
  {
    "name": "Dr. Shruti Bansal",
    "age": 35,
    "degree": "Anesthesiology",
    "experience": 7,
    "gender": "Female",
    "rating": 4,
    "fees": "300",
    "city": "Thane",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Sanjay Joshi",
    "age": 53,
    "degree": "Orthopedics",
    "experience": 17,
    "gender": "Male",
    "rating": 5,
    "fees": "450",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh"
  },
  {
    "name": "Dr. Riya Gupta",
    "age": 40,
    "degree": "General Medicine",
    "experience": 19,
    "gender": "Female",
    "rating": 4,
    "fees": "350",
    "city": "Surat",
    "state": "Gujarat"
  },
  {
    "name": "Dr. Vinod Mehta",
    "age": 32,
    "degree": "Oncology",
    "experience": 11,
    "gender": "Male",
    "rating": 2,
    "fees": "280",
    "city": "Agra",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Ritu Singh",
    "age": 51,
    "degree": "Psychiatry",
    "experience": 24,
    "gender": "Female",
    "rating": 3,
    "fees": "320",
    "city": "Varanasi",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Prakash Patel",
    "age": 30,
    "degree": "Nephrology",
    "experience": 13,
    "gender": "Male",
    "rating": 1,
    "fees": "200",
    "city": "Coimbatore",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Pooja Gupta",
    "age": 45,
    "degree": "Geriatrics",
    "experience": 21,
    "gender": "Female",
    "rating": 4,
    "fees": "420",
    "city": "Chandigarh",
    "state": "Chandigarh"
  },
  {
    "name": "Dr. Sameer Khan",
    "age": 27,
    "degree": "Allergy and Immunology",
    "experience": 9,
    "gender": "Male",
    "rating": 5,
    "fees": "350",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Manisha Sharma",
    "age": 49,
    "degree": "Physical Medicine and Rehabilitation",
    "experience": 16,
    "gender": "Female",
    "rating": 4,
    "fees": "380",
    "city": "Delhi",
    "state": "Delhi"
  },
  {
    "name": "Dr. Rajiv Kapoor",
    "age": 41,
    "degree": "Emergency Medicine",
    "experience": 8,
    "gender": "Male",
    "rating": 3,
    "fees": "250",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Kavita Reddy",
    "age": 34,
    "degree": "Otolaryngology (ENT)",
    "experience": 15,
    "gender": "Female",
    "rating": 2,
    "fees": "300",
    "city": "Bangalore",
    "state": "Karnataka"
  },
  {
    "name": "Dr. Anil Kumar",
    "age": 55,
    "degree": "Plastic Surgery",
    "experience": 27,
    "gender": "Male",
    "rating": 5,
    "fees": "500",
    "city": "Chennai",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Renuka Deshmukh",
    "age": 26,
    "degree": "Vascular Surgery",
    "experience": 4,
    "gender": "Female",
    "rating": 1,
    "fees": "150",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "name": "Dr. Vikas Tiwari",
    "age": 38,
    "degree": "Pediatric Surgery",
    "experience": 19,
    "gender": "Male",
    "rating": 4,
    "fees": "400",
    "city": "Kolkata",
    "state": "West Bengal"
  },
  {
    "name": "Dr. Rekha Singh",
    "age": 29,
    "degree": "Neurosurgery",
    "experience": 10,
    "gender": "Female",
    "rating": 3,
    "fees": "350",
    "city": "Pune",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Sumit Kapoor",
    "age": 47,
    "degree": "Thoracic Surgery",
    "experience": 25,
    "gender": "Male",
    "rating": 4,
    "fees": "450",
    "city": "Ahmedabad",
    "state": "Gujarat"
  },
  {
    "name": "Dr. Aishwarya Gupta",
    "age": 36,
    "degree": "Pain Medicine",
    "experience": 16,
    "gender": "Female",
    "rating": 2,
    "fees": "250",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rohit Sharma",
    "age": 51,
    "degree": "Sports Medicine",
    "experience": 28,
    "gender": "Male",
    "rating": 4,
    "fees": "380",
    "city": "Lucknow",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Ananya Verma",
    "age": 30,
    "degree": "Pathology",
    "experience": 12,
    "gender": "Female",
    "rating": 5,
    "fees": "400",
    "city": "Chandigarh",
    "state": "Chandigarh"
  },
  {
    "name": "Dr. Rajeev Kumar",
    "age": 40,
    "degree": "Gynecologic Oncology",
    "experience": 18,
    "gender": "Male",
    "rating": 3,
    "fees": "300",
    "city": "Delhi",
    "state": "Delhi"
  },
  {
    "name": "Dr. Deepak Singh",
    "age": 33,
    "degree": "Neonatology",
    "experience": 15,
    "gender": "Male",
    "rating": 4,
    "fees": "350",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Smita Desai",
    "age": 49,
    "degree": "Forensic Medicine",
    "experience": 24,
    "gender": "Female",
    "rating": 2,
    "fees": "200",
    "city": "Bangalore",
    "state": "Karnataka"
  },
  {
    "name": "Dr. Sanjeev Sharma",
    "age": 28,
    "degree": "Palliative Medicine",
    "experience": 7,
    "gender": "Male",
    "rating": 4,
    "fees": "275",
    "city": "Chennai",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Priyanka Reddy",
    "age": 44,
    "degree": "Sleep Medicine",
    "experience": 20,
    "gender": "Female",
    "rating": 5,
    "fees": "450",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "name": "Dr. Alok Verma",
    "age": 36,
    "degree": "Reproductive Medicine",
    "experience": 13,
    "gender": "Male",
    "rating": 3,
    "fees": "300",
    "city": "Kolkata",
    "state": "West Bengal"
  },
  {
    "name": "Dr. Roshan Gupta",
    "age": 45,
    "degree": "Interventional Radiology",
    "experience": 22,
    "gender": "Male",
    "rating": 4,
    "fees": "400",
    "city": "Pune",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Neha Kapoor",
    "age": 29,
    "degree": "Nuclear Medicine",
    "experience": 11,
    "gender": "Female",
    "rating": 1,
    "fees": "150",
    "city": "Ahmedabad",
    "state": "Gujarat"
  },
  {
    "name": "Dr. Akshay Kumar",
    "age": 50,
    "degree": "Clinical Genetics",
    "experience": 27,
    "gender": "Male",
    "rating": 4,
    "fees": "350",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Preeti Singh",
    "age": 31,
    "degree": "Addiction Medicine",
    "experience": 8,
    "gender": "Female",
    "rating": 5,
    "fees": "380",
    "city": "Lucknow",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Arvind Sharma",
    "age": 52,
    "degree": "Aerospace Medicine",
    "experience": 29,
    "gender": "Male",
    "rating": 4,
    "fees": "400",
    "city": "Chandigarh",
    "state": "Chandigarh"
  },
  {
    "name": "Dr. Anjali Gupta",
    "age": 41,
    "degree": "Colorectal Surgery",
    "experience": 18,
    "gender": "Female",
    "rating": 3,
    "fees": "300",
    "city": "Delhi",
    "state": "Delhi"
  },
  {
    "name": "Dr. Ramesh Tiwari",
    "age": 38,
    "degree": "Hand Surgery",
    "experience": 16,
    "gender": "Male",
    "rating": 2,
    "fees": "250",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Seema Verma",
    "age": 42,
    "degree": "Infectious Disease Medicine",
    "experience": 17,
    "gender": "Female",
    "rating": 4,
    "fees": "350",
    "city": "Bangalore",
    "state": "Karnataka"
  },
  {
    "name": "Dr. Rajesh Gupta",
    "age": 39,
    "degree": "Interventional Cardiology",
    "experience": 14,
    "gender": "Male",
    "rating": 5,
    "fees": "400",
    "city": "Chennai",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Meera Kapoor",
    "age": 34,
    "degree": "Medical Genetics",
    "experience": 11,
    "gender": "Female",
    "rating": 3,
    "fees": "275",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "name": "Dr. Sunil Kumar",
    "age": 49,
    "degree": "General Dentistry",
    "experience": 23,
    "gender": "Male",
    "rating": 4,
    "fees": "350",
    "city": "Kolkata",
    "state": "West Bengal"
  },
  {
    "name": "Dr. Anita Reddy",
    "age": 35,
    "degree": "Orthodontics",
    "experience": 14,
    "gender": "Female",
    "rating": 2,
    "fees": "250",
    "city": "Pune",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Vikram Tiwari",
    "age": 43,
    "degree": "Pediatric Dentistry (Pedodontics)",
    "experience": 19,
    "gender": "Male",
    "rating": 4,
    "fees": "350",
    "city": "Ahmedabad",
    "state": "Gujarat"
  },
  {
    "name": "Dr. Neha Sharma",
    "age": 30,
    "degree": "Oral and Maxillofacial Surgery",
    "experience": 12,
    "gender": "Female",
    "rating": 5,
    "fees": "400",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Manoj Kumar",
    "age": 46,
    "degree": "Periodontics",
    "experience": 20,
    "gender": "Male",
    "rating": 4,
    "fees": "380",
    "city": "Lucknow",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Kirti Mehta",
    "age": 32,
    "degree": "Prosthodontics",
    "experience": 9,
    "gender": "Female",
    "rating": 3,
    "fees": "300",
    "city": "Chandigarh",
    "state": "Chandigarh"
  },
  {
    "name": "Dr. Rakesh Sharma",
    "age": 54,
    "degree": "Endodontics",
    "experience": 26,
    "gender": "Male",
    "rating": 4,
    "fees": "350",
    "city": "Delhi",
    "state": "Delhi"
  },
  {
    "name": "Dr. Nisha Patel",
    "age": 29,
    "degree": "Oral Pathology",
    "experience": 10,
    "gender": "Female",
    "rating": 2,
    "fees": "250",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Karan Kapoor",
    "age": 47,
    "degree": "Dental Public Health",
    "experience": 24,
    "gender": "Male",
    "rating": 5,
    "fees": "450",
    "city": "Bangalore",
    "state": "Karnataka"
  },
  {
    "name": "Dr. Preeti Verma",
    "age": 31,
    "degree": "Oral Medicine",
    "experience": 13,
    "gender": "Female",
    "rating": 1,
    "fees": "200",
    "city": "Chennai",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Sameer Kumar",
    "age": 45,
    "degree": "Cosmetic Dentistry",
    "experience": 22,
    "gender": "Male",
    "rating": 4,
    "fees": "400",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "name": "Dr. Priya Sharma",
    "age": 37,
    "degree": "Implant Dentistry",
    "experience": 15,
    "gender": "Female",
    "rating": 3,
    "fees": "350",
    "city": "Kolkata",
    "state": "West Bengal"
  },
  {
    "name": "Dr. Amit Patel",
    "age": 40,
    "degree": "Restorative Dentistry",
    "experience": 18,
    "gender": "Male",
    "rating": 2,
    "fees": "300",
    "city": "Pune",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Rishabh Kapoor",
    "age": 40,
    "degree": "Dermatology",
    "experience": 15,
    "gender": "Male",
    "rating": 4,
    "fees": "700",
    "city": "Mumbai",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Sneha Sharma",
    "age": 36,
    "degree": "Gynecologic Oncology",
    "experience": 12,
    "gender": "Female",
    "rating": 5,
    "fees": "800",
    "city": "Delhi",
    "state": "Delhi"
  },
  {
    "name": "Dr. Arvind Verma",
    "age": 51,
    "degree": "Neurosurgery",
    "experience": 28,
    "gender": "Male",
    "rating": 4,
    "fees": "900",
    "city": "Bangalore",
    "state": "Karnataka"
  },
  {
    "name": "Dr. Nidhi Gupta",
    "age": 45,
    "degree": "Cardiology",
    "experience": 22,
    "gender": "Female",
    "rating": 3,
    "fees": "750",
    "city": "Chennai",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Vikram Kumar",
    "age": 55,
    "degree": "Urology",
    "experience": 30,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Hyderabad",
    "state": "Telangana"
  },
  {
    "name": "Dr. Pooja Verma",
    "age": 34,
    "degree": "Orthopedics",
    "experience": 8,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Kolkata",
    "state": "West Bengal"
  },
  {
    "name": "Dr. Sameer Kapoor",
    "age": 47,
    "degree": "Pediatric Surgery",
    "experience": 24,
    "gender": "Male",
    "rating": 4,
    "fees": "800",
    "city": "Pune",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Neha Sharma",
    "age": 29,
    "degree": "Anesthesiology",
    "experience": 6,
    "gender": "Female",
    "rating": 3,
    "fees": "600",
    "city": "Ahmedabad",
    "state": "Gujarat"
  },
  {
    "name": "Dr. Rahul Verma",
    "age": 42,
    "degree": "Ophthalmology",
    "experience": 20,
    "gender": "Male",
    "rating": 4,
    "fees": "700",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Priyanka Kapoor",
    "age": 35,
    "degree": "Radiology",
    "experience": 10,
    "gender": "Female",
    "rating": 1,
    "fees": "500",
    "city": "Lucknow",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Anand Verma",
    "age": 41,
    "degree": "Dental Public Health",
    "experience": 18,
    "gender": "Male",
    "rating": 5,
    "fees": "900",
    "city": "Nagpur",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Neha Gupta",
    "age": 38,
    "degree": "Pulmonology",
    "experience": 16,
    "gender": "Female",
    "rating": 4,
    "fees": "750",
    "city": "Indore",
    "state": "Madhya Pradesh"
  },
  {
    "name": "Dr. Karan Sharma",
    "age": 32,
    "degree": "Hematology",
    "experience": 14,
    "gender": "Male",
    "rating": 3,
    "fees": "650",
    "city": "Thane",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Ritu Kapoor",
    "age": 48,
    "degree": "Endocrinology",
    "experience": 25,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh"
  },
  {
    "name": "Dr. Rajat Sharma",
    "age": 37,
    "degree": "Allergy and Immunology",
    "experience": 9,
    "gender": "Male",
    "rating": 4,
    "fees": "700",
    "city": "Surat",
    "state": "Gujarat"
  },
  {
    "name": "Dr. Neha Verma",
    "age": 30,
    "degree": "Family Medicine",
    "experience": 6,
    "gender": "Female",
    "rating": 5,
    "fees": "550",
    "city": "Agra",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Rohan Kapoor",
    "age": 43,
    "degree": "Geriatrics",
    "experience": 19,
    "gender": "Male",
    "rating": 3,
    "fees": "600",
    "city": "Varanasi",
    "state": "Uttar Pradesh"
  },
  {
    "name": "Dr. Preeti Sharma",
    "age": 28,
    "degree": "Infectious Disease",
    "experience": 5,
    "gender": "Female",
    "rating": 4,
    "fees": "500",
    "city": "Coimbatore",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Rahul Verma",
    "age": 40,
    "degree": "Addiction Medicine",
    "experience": 18,
    "gender": "Male",
    "rating": 3,
    "fees": "600",
    "city": "Chandigarh",
    "state": "Chandigarh"
  },
  {
    "name": "Dr. Nisha Kapoor",
    "age": 33,
    "degree": "Aerospace Medicine",
    "experience": 15,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Ludhiana",
    "state": "Punjab"
  },
  {
    "name": "Dr. Karan Verma",
    "age": 44,
    "degree": "Colorectal Surgery",
    "experience": 21,
    "gender": "Male",
    "rating": 1,
    "fees": "500",
    "city": "Raipur",
    "state": "Chhattisgarh"
  },
  {
    "name": "Dr. Neha Sharma",
    "age": 31,
    "degree": "Hand Surgery",
    "experience": 7,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Patna",
    "state": "Bihar"
  },
  {
    "name": "Dr. Rahul Kapoor",
    "age": 55,
    "degree": "Infectious Disease Medicine",
    "experience": 29,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Ranchi",
    "state": "Jharkhand"
  },
  {
    "name": "Dr. Nidhi Verma",
    "age": 27,
    "degree": "Interventional Cardiology",
    "experience": 4,
    "gender": "Female",
    "rating": 3,
    "fees": "550",
    "city": "Guwahati",
    "state": "Assam"
  },
  {
    "name": "Dr. Rohit Kapoor",
    "age": 41,
    "degree": "Medical Genetics",
    "experience": 17,
    "gender": "Male",
    "rating": 4,
    "fees": "700",
    "city": "Amritsar",
    "state": "Punjab"
  },
  {
    "name": "Dr. Priya Sharma",
    "age": 29,
    "degree": "General Dentistry",
    "experience": 6,
    "gender": "Female",
    "rating": 2,
    "fees": "500",
    "city": "Vijayawada",
    "state": "Andhra Pradesh"
  },
  {
    "name": "Dr. Rajat Verma",
    "age": 53,
    "degree": "Orthodontics",
    "experience": 23,
    "gender": "Male",
    "rating": 5,
    "fees": "900",
    "city": "Nashik",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Ritu Kapoor",
    "age": 39,
    "degree": "Pediatric Dentistry (Pedodontics)",
    "experience": 16,
    "gender": "Female",
    "rating": 4,
    "fees": "800",
    "city": "Madurai",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Sumeet Verma",
    "age": 31,
    "degree": "Oral and Maxillofacial Surgery",
    "experience": 8,
    "gender": "Male",
    "rating": 3,
    "fees": "650",
    "city": "Mysore",
    "state": "Karnataka"
  },
  {
    "name": "Dr. Priyanka Kapoor",
    "age": 47,
    "degree": "Periodontics",
    "experience": 24,
    "gender": "Female",
    "rating": 5,
    "fees": "900",
    "city": "Aurangabad",
    "state": "Maharashtra"
  },
  {
    "name": "Dr. Rohit Verma",
    "age": 30,
    "degree": "Prosthodontics",
    "experience": 6,
    "gender": "Male",
    "rating": 4,
    "fees": "600",
    "city": "Cuttack",
    "state": "Odisha"
  },
  {
    "name": "Dr. Nandini Sharma",
    "age": 45,
    "degree": "Endodontics",
    "experience": 20,
    "gender": "Female",
    "rating": 3,
    "fees": "750",
    "city": "Bhubaneswar",
    "state": "Odisha"
  },
  {
    "name": "Dr. Karan Kapoor",
    "age": 35,
    "degree": "Oral Pathology",
    "experience": 12,
    "gender": "Male",
    "rating": 4,
    "fees": "700",
    "city": "Salem",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Sneha Verma",
    "age": 49,
    "degree": "Dental Public Health",
    "experience": 25,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Tiruchirappalli",
    "state": "Tamil Nadu"
  },
  {
    "name": "Dr. Ravi Kapoor",
    "age": 38,
    "degree": "Oral Medicine",
    "experience": 16,
    "gender": "Male",
    "rating": 4,
    "fees": "600",
    "city": "Kota",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Neha Verma",
    "age": 36,
    "degree": "Oral and Maxillofacial Radiology",
    "experience": 11,
    "gender": "Female",
    "rating": 3,
    "fees": "650",
    "city": "Bikaner",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rohan Kapoor",
    "age": 44,
    "degree": "Oral and Maxillofacial Pathology",
    "experience": 21,
    "gender": "Male",
    "rating": 1,
    "fees": "500",
    "city": "Ajmer",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Pooja Verma",
    "age": 29,
    "degree": "Orthodontics",
    "experience": 7,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Udaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Sumeet Kapoor",
    "age": 55,
    "degree": "Pediatric Dentistry (Pedodontics)",
    "experience": 28,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Jodhpur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Priyanka Verma",
    "age": 27,
    "degree": "Periodontics",
    "experience": 4,
    "gender": "Female",
    "rating": 4,
    "fees": "800",
    "city": "Sikar",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rajat Kapoor",
    "age": 45,
    "degree": "Prosthodontics",
    "experience": 22,
    "gender": "Male",
    "rating": 3,
    "fees": "750",
    "city": "Bharatpur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Neha Kapoor",
    "age": 33,
    "degree": "Endodontics",
    "experience": 15,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Kishangarh",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rohit Verma",
    "age": 52,
    "degree": "Oral Pathology",
    "experience": 28,
    "gender": "Male",
    "rating": 5,
    "fees": "900",
    "city": "Tonk",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Sneha Kapoor",
    "age": 28,
    "degree": "Dental Public Health",
    "experience": 5,
    "gender": "Female",
    "rating": 4,
    "fees": "600",
    "city": "Sirohi",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Arvind Verma",
    "age": 40,
    "degree": "Oral Medicine",
    "experience": 18,
    "gender": "Male",
    "rating": 3,
    "fees": "650",
    "city": "Pali",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Nidhi Kapoor",
    "age": 34,
    "degree": "Oral and Maxillofacial Radiology",
    "experience": 11,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Bhilwara",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Vikram Verma",
    "age": 48,
    "degree": "Oral and Maxillofacial Pathology",
    "experience": 25,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Chittorgarh",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Pooja Sharma",
    "age": 31,
    "degree": "Orthodontics",
    "experience": 7,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Dausa",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Sumeet Verma",
    "age": 39,
    "degree": "Pediatric Dentistry (Pedodontics)",
    "experience": 16,
    "gender": "Male",
    "rating": 3,
    "fees": "750",
    "city": "Hanumangarh",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Priyanka Verma",
    "age": 32,
    "degree": "Periodontics",
    "experience": 8,
    "gender": "Female",
    "rating": 2,
    "fees": "650",
    "city": "Karauli",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rajat Verma",
    "age": 47,
    "degree": "Prosthodontics",
    "experience": 24,
    "gender": "Male",
    "rating": 1,
    "fees": "600",
    "city": "Jaisalmer",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Neha Kapoor",
    "age": 28,
    "degree": "Endodontics",
    "experience": 6,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Jhunjhunu",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rohit Verma",
    "age": 54,
    "degree": "Oral Pathology",
    "experience": 29,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Bikaner",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Sneha Kapoor",
    "age": 29,
    "degree": "Dental Public Health",
    "experience": 6,
    "gender": "Female",
    "rating": 4,
    "fees": "800",
    "city": "Bharatpur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Arvind Verma",
    "age": 43,
    "degree": "Oral Medicine",
    "experience": 21,
    "gender": "Male",
    "rating": 3,
    "fees": "650",
    "city": "Kishangarh",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Nidhi Kapoor",
    "age": 31,
    "degree": "Oral and Maxillofacial Radiology",
    "experience": 9,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Ajmer",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Vikram Verma",
    "age": 52,
    "degree": "Oral and Maxillofacial Pathology",
    "experience": 28,
    "gender": "Male",
    "rating": 5,
    "fees": "900",
    "city": "Alwar",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Pooja Sharma",
    "age": 40,
    "degree": "Orthodontics",
    "experience": 17,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Baran",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Sumeet Verma",
    "age": 35,
    "degree": "Pediatric Dentistry (Pedodontics)",
    "experience": 12,
    "gender": "Male",
    "rating": 3,
    "fees": "750",
    "city": "Beawar",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Priyanka Verma",
    "age": 47,
    "degree": "Periodontics",
    "experience": 24,
    "gender": "Female",
    "rating": 2,
    "fees": "650",
    "city": "Bhilwara",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rajat Verma",
    "age": 38,
    "degree": "Prosthodontics",
    "experience": 16,
    "gender": "Male",
    "rating": 1,
    "fees": "600",
    "city": "Bundi",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Neha Kapoor",
    "age": 36,
    "degree": "Endodontics",
    "experience": 11,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Chittorgarh",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rohit Verma",
    "age": 50,
    "degree": "Oral Pathology",
    "experience": 26,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Dhaulpur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Sneha Kapoor",
    "age": 27,
    "degree": "Dental Public Health",
    "experience": 4,
    "gender": "Female",
    "rating": 4,
    "fees": "800",
    "city": "Hanumangarh",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Arvind Verma",
    "age": 37,
    "degree": "Oral Medicine",
    "experience": 15,
    "gender": "Male",
    "rating": 3,
    "fees": "650",
    "city": "Pali",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Nidhi Kapoor",
    "age": 33,
    "degree": "Oral and Maxillofacial Radiology",
    "experience": 10,
    "gender": "Female",
    "rating": 2,
    "fees": "550",
    "city": "Sawai Madhopur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Vikram Verma",
    "age": 49,
    "degree": "Oral and Maxillofacial Pathology",
    "experience": 26,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Sikar",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Pooja Sharma",
    "age": 32,
    "degree": "Orthodontics",
    "experience": 7,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Sri Ganganagar",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Sumeet Verma",
    "age": 48,
    "degree": "Pediatric Dentistry (Pedodontics)",
    "experience": 25,
    "gender": "Male",
    "rating": 3,
    "fees": "750",
    "city": "Tonk",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Priyanka Verma",
    "age": 36,
    "degree": "Periodontics",
    "experience": 13,
    "gender": "Female",
    "rating": 2,
    "fees": "650",
    "city": "Udaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rajat Verma",
    "age": 45,
    "degree": "Prosthodontics",
    "experience": 22,
    "gender": "Male",
    "rating": 1,
    "fees": "600",
    "city": "Jaipur",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Neha Kapoor",
    "age": 31,
    "degree": "Endodontics",
    "experience": 9,
    "gender": "Female",
    "rating": 4,
    "fees": "700",
    "city": "Kota",
    "state": "Rajasthan"
  },
  {
    "name": "Dr. Rohit Verma",
    "age": 55,
    "degree": "Oral Pathology",
    "experience": 29,
    "gender": "Male",
    "rating": 5,
    "fees": "950",
    "city": "Kishangarh",
    "state": "Rajasthan"
  }
]
