export const majorCitiesArray = [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Surat",
    "Agra",
    "Varanasi",
    "Coimbatore",
    "Chandigarh",
    "Ludhiana",
    "Raipur",
    "Patna",
    "Ranchi",
    "Guwahati",
    "Amritsar",
    "Vijayawada",
    "Nashik",
    "Madurai",
    "Mysore",
    "Aurangabad",
    "Cuttack",
    "Bhubaneswar",
    "Salem",
    "Tiruchirappalli",
    "Kota",
    "Kochi (Cochin)",
    "Aligarh",
    "Bareilly",
    "Moradabad",
    "Jalandhar",
    "Jamshedpur",
    "Dehradun",
    "Dhanbad",
    "Gorakhpur",
    "Warangal",
    "Guntur",
    "Jammu",
    "Jalgaon",
    "Nellore",
    "Ajmer",
    "Bikaner",
    "Srinagar",
    "Amravati",
    "Rajahmundry",
    "Shimla",
    "Tirupati",
    "Ujjain",
    "Siliguri",
    "Nanded",
    "Rourkela",
    "Durgapur",
    "Allahabad",
    "Davanagere",
    "Jhansi",
    "Asansol",
    "Tirunelveli",
    "Kolhapur",
    "Gwalior",
    "Latur",
    "Gandhinagar",
    "Noida",
    "Thiruvananthapuram",
    "Meerut",
    "Mathura",
    "Bilaspur",
    "Solapur",
    "Dhule",
    "Durg",
    "Gaya",
    "Nalanda",
    "Bhagalpur",
    "Saharsa",
    "Rohtak",
    "Hisar",
    "Panipat",
    "Sonipat",
    "Karnal",
    "Rewari",
    "Palwal",
    "Bahadurgarh",
    "Yamunanagar",
    "Kurukshetra",
    "Faridabad",
    "Panchkula",
    "Ambala"
  ];
  
 export const specialtiesArray = [
    "General Medicine",
    "Pediatrics",
    "Obstetrics and Gynecology",
    "Cardiology",
    "Dermatology",
    "Orthopedics",
    "Ophthalmology",
    "Gastroenterology",
    "Neurology",
    "Psychiatry",
    "Nephrology",
    "Urology",
    "Radiology",
    "Anesthesiology",
    "Oncology",
    "Pulmonology",
    "Rheumatology",
    "Endocrinology",
    "Hematology",
    "Infectious Disease",
    "Family Medicine",
    "Geriatrics",
    "Allergy and Immunology",
    "Physical Medicine and Rehabilitation",
    "Emergency Medicine",
    "Otolaryngology (ENT)",
    "Plastic Surgery",
    "Vascular Surgery",
    "Pediatric Surgery",
    "Neurosurgery",
    "Thoracic Surgery",
    "Pain Medicine",
    "Sports Medicine",
    "Pathology",
    "Gynecologic Oncology",
    "Neonatology",
    "Forensic Medicine",
    "Palliative Medicine",
    "Sleep Medicine",
    "Reproductive Medicine",
    "Interventional Radiology",
    "Nuclear Medicine",
    "Clinical Genetics",
    "Addiction Medicine",
    "Aerospace Medicine",
    "Colorectal Surgery",
    "Hand Surgery",
    "Infectious Disease Medicine",
    "Interventional Cardiology",
    "Medical Genetics",
    "General Dentistry",
    "Orthodontics",
    "Pediatric Dentistry (Pedodontics)",
    "Oral and Maxillofacial Surgery",
    "Periodontics",
    "Prosthodontics",
    "Endodontics",
    "Oral Pathology",
    "Dental Public Health",
    "Oral Medicine",
    "Cosmetic Dentistry",
    "Implant Dentistry",
    "Restorative Dentistry"
  ];
  